### ISSUE TITLE
bgzipped reference

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_CANRISK_vcf#3]
Consider requiring a bgzipped reference as input, rather than performing the bgzip each time the app is run

**Comment by sophie22** [comment]
reference genome fasta needs to have an index file available. simplest might be to provide that as an input too

**Comment by sophie22** [comment]
when a .fa.fai is provided, the "original" .fa.gz input file needs to be gunzipped (which takes some time)
will compare whether unzipping with index file or bgzipping takes shorter?

**Comment by sophie22** [comment]
gunzip + index: about a minute
![image](https://github.com/eastgenomics/eggd_CANRISK_vcf/assets/15593138/2f1189bd-d83e-4436-a1d8-b6cb7ef2adcf)

bgzip: about 5 and a half minutes
![image](https://github.com/eastgenomics/eggd_CANRISK_vcf/assets/15593138/3155556a-bcfe-4cdb-8db4-6445aa154d7c)

**Comment by sophie22** [comment]
resolved by #5
